#!/bin/bash
cd "$(dirname "$0")"
source ./script/setup.sh

# 1. It takes 300ms for cmd-help to generate. It's too long to run in build-debug.sh, that's why we ignore it
# 2. Grammar is not expected to change very often, that's why it's not regenerated by default
./generate.sh --ignore-xcodeproj --ignore-cmd-help --ignore-shell-parser
swift build "$@"
# Tests are built and run via ./run-swift-test.sh in run-tests.sh.
# Building a test target directly with `swift build --target ...` treats it as a
# non-test target and can fail to resolve XCTest on some local toolchains.

rm -rf .debug && mkdir .debug
cp -r .build/debug/aerospace .debug
cp -r .build/debug/AeroSpaceApp .debug
