name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: macos-15
    permissions:
      contents: write
    defaults:
      run:
        working-directory: AeroSpace

    steps:
      - uses: actions/checkout@v6
        with:
          path: AeroSpace

      - run: ./.github/gh-actions-runner-xcode-select.sh

      - run: brew install bash fish xcbeautify

      - name: Build release
        run: |
          ./build-release.sh --codesign-identity - --build-version "${{ github.ref_name }}"

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: AeroSpace/.release/NiriSpace-${{ github.ref_name }}.zip
          generate_release_notes: true
